### ISSUE TITLE
question!

### ISSUE THREAD

**Issue by slaygirlz** [SplinterHead/ha-honeygain#5]
how do i know this is safe and not going to ban me!

**Comment by SplinterHead** [comment]
Im not associated with Honeygain, but I haven't had any issues and I've been running it for over a year. I've already had a payout from them and I have another built up, so I know they're legit that way. It just sits there on the server, earning a trickle of money

Here's some information about their security
https://support.honeygain.com/hc/en-us/articles/360013229920-Is-Honeygain-safe-What-user-data-is-being-collected

There's also a ton of good reviews on TrustPilot 
https://uk.trustpilot.com/review/honeygain.com

**Comment by slaygirlz** [comment]
sorry i do use honeygain, i was mentioning this project!

**Comment by SplinterHead** [comment]
Ahh apologies, 

So the Honeygain API doesn't seem to have rate limits, but HA doesn't seem to be spamming the endpoint anyway. 

I've been running this integration of my server for about 6 months solid and not had any issues

**Comment by slaygirlz** [comment]
thank u
